Moving some stuff into functions

diff --git a/bash-migrate b/bash-migrate
--- a/bash-migrate
+++ b/bash-migrate
@@ -2,7 +2,18 @@
 
 set -euo pipefail
 
-SCRIPT_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+##############################
+# Print error message and exit
+# Arguments:
+#   $1: message
+#   $2: exit code (default 1)
+##############################
+function die()
+{
+  declare message="$1" exitcode="${2:-1}"
+  echo "$message" >&2
+  exit $exitcode
+}
 
 #########################
 # Default config values #
@@ -24,42 +35,33 @@ do
       shift
       ;;
     *)
-      echo "Unknown option $OPTION" >&2
-      exit 1
+      die "Unknown option $OPTION"
       ;;
   esac
 done
 
+#################################################
+# Loads the config and checks for required values
+# Globals:
+#   CONFIG_FILE: name of the config file to use
+#   SCRIPT_HOME: location of the main script
+#   *: adds values from config file
+#################################################
+function load_config() {
+  #TODO: move SCRIPT_HOME calculation into here?
+  source "$CONFIG_FILE"
+  if [[ -z "${MIGRATION_DIR:-}" ]]; then
+    die "Missing required config value MIGRATION_DIR"
+  fi
+  if [[ ! -d "$MIGRATION_DIR" ]]; then
+    die "Migration directory $MIGRATION_DIR not found"
+  fi
+}
+
 #################################
 # Load and Validate Config File #
 #################################
-
-source "$CONFIG_FILE"
-
-if [[ -z "${DB_TYPE:-}" ]]
-then
-   echo "Missing required config value DB_TYPE" >&2
-   exit 1
-fi
-
-# Load migration functions for specified database type
-if [[ ! -f "$SCRIPT_HOME/bash-migrate-$DB_TYPE" ]]
-then
-  echo "Unknown DB_TYPE: $DB_TYPE" >&2
-  exit 1
-fi
-
-if [[ -z "${MIGRATION_DIR:-}" ]]
-then
-   echo "Missing required config value MIGRATION_DIR" >&2
-   exit 1
-fi
-
-if [[ ! -d "$MIGRATION_DIR" ]]
-then
-   echo "Migration directory $MIGRATION_DIR not found" >&2
-   exit 1
-fi
+load_config
 
 #############################
 # Parse and execute command #
@@ -106,8 +108,28 @@ EOF
 # TODO: store most of the stuff below in a separate script that can be
 #       run in a subshell in order to support multiple migration dirs at once?
 
-# Load in DB_TYPE specific implementations for functions
-source "$SCRIPT_HOME/bash-migrate-$DB_TYPE"
+###########################################
+# Load in database specific implementations
+# Arguments:
+#   db_type
+########################################### 
+function load_db_files() {
+  local db_type="$1"
+
+  if [[ -z "${db_type}" ]]; then
+    die "Missing required config value DB_TYPE"
+  fi
+
+  local db_script="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/bash-migrate-$db_type"
+  
+  if [[ ! -f "$db_script" ]]; then
+    die "Unknown database type: $db_type"
+  fi
+
+  source "$db_script"
+}
+
+load_db_files "${DB_TYPE:-}"
 
 case "$COMMAND" in
   migrate)
@@ -132,11 +154,11 @@ case "$COMMAND" in
 
     find "$MIGRATION_DIR" -regex "$MIGRATION_DIR/[0-9]+_$MIGRATION_NAME.\(up\|down\).$MIGRATION_FILE_EXTENSION" -type f | grep -q "." && { echo "Migration with name $MIGRATION_NAME already exists" >&2; exit 1; }
 
-
     TIMESTAMP=$( date +%s )
-    touch "$MIGRATION_DIR/${TIMESTAMP}_$MIGRATION_NAME.up.$MIGRATION_FILE_EXTENSION"
-    touch "$MIGRATION_DIR/${TIMESTAMP}_$MIGRATION_NAME.down.$MIGRATION_FILE_EXTENSION"
-    echo "Created $MIGRATION_DIR/${TIMESTAMP}_$MIGRATION_NAME.(up|down).$MIGRATION_FILE_EXTENSION"
+    UP_FILE="$MIGRATION_DIR/${TIMESTAMP}_$MIGRATION_NAME.up.$MIGRATION_FILE_EXTENSION"
+    DOWN_FILE="$MIGRATION_DIR/${TIMESTAMP}_$MIGRATION_NAME.down.$MIGRATION_FILE_EXTENSION"
+    touch "$UP_FILE" && echo "Created $UP_FILE"
+    touch "$DOWN_FILE" && echo "Created $DOWN_FILE"
     ;;
   help)
     showhelp
